version: '3.9'

services:
  greenlight_api:
    container_name: greenlight_api
    build: .
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    depends_on:
      - greenlight_db
    command: go run ./cmd/api
  greenlight_db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5430:5432'
    volumes:
      - greenlight_db_data:/var/lib/postgresql/data

volumes:
  greenlight_db_data:
